fixdat_aam = data.table(original = c("Other", "< 16", "", "Not 16", "<= 16", "NA", "Any", "< 15", 
                                     "Multistep Condition", "> 16", 
                                     "(AGE_AT_MIGRATION BETWEEN 13 AND 18) & (AGE_AT_MIGRATION < 16)", 
                                     "(AGE_AT_MIGRATION BETWEEN 15 AND 16) & (AGE_AT_MIGRATION == 15)", 
                                     "AGE_AT_MIGRATION BETWEEN 14 AND 15", "YEAR < 2012 | !(AGE_AT_MIGRATION BETWEEN 0 AND 15) | AGE_IN_2012 >= 31 | YRIMMIG > 2007 | CITIZEN != 3", 
                                     "(AGE_AT_MIGRATION != 16) & (AGE_AT_MIGRATION >= 16 | AGE_IN_2012 >= 31 | YRIMMIG >= 2008 | (YEAR - YRSUSA1 > 2007) | YEAR <= 2012)", 
                                     "(AGE_AT_MIGRATION < 16) & ((BIRTHYR BETWEEN 1978 AND 1980 | (BIRTHYR == 1977 & BIRTHQTR > 2) | (BIRTHYR == 1981 & BIRTHQTR < 3) & HISPAN BETWEEN 1 AND 4 & (BPLD != 20000 & BPL != 999) & (YRIMMIG BETWEEN 997 AND 2006) & AGE_AT_MIGRATION < 16 & (EDUCD >= 60 | VETSTAT == 2) & (AGE_IN_2012 >= 31 | YEAR < 2012))", 
                                     "AGE_AT_MIGRATION >= 16 | YRIMMIG > 2007 | BIRTHYR > 1981 | CITIZEN != 3 | YEAR <= 2012", "AGE_AT_MIGRATION >= 16 | CITIZEN != 3 | AGE_IN_2012 >= 31 | YRSUSA1 < 5 | YRIMMIG > 2007", "(AGE_AT_MIGRATION BETWEEN 0 AND 22) & (AGE > AGE_AT_MIGRATION) & (AGE_AT_MIGRATION >= 16 | AGE_IN_2012 >= 31 | YEAR <= 2012)", 
                                     "(AGE_AT_MIGRATION BETWEEN 12 AND 20) & (AGE_AT_MIGRATION > 16)", "(AGE_AT_MIGRATION > 10) & (AGE_AT_MIGRATION < 11)", "CITIZEN != 3 | !(EDUC >= 6 | VETSTAT == 2) | AGE_AT_MIGRATION >= 16 | AGE_IN_2012 > 31 | (2012 - BIRTHYR <= 25) | BPL != 200 | MIGPLAC1 >= 100 | YRNATUR < 2013 | YRIMMIG > 2012", 
                                     "(AGE_AT_MIGRATION != 16) & (!(AGE_AT_MIGRATION < 16) | !(AGE_IN_2012 < 31) | (YRIMMIG < 2007) | !(EDUC >= 6 | VETSTAT == 2) | !(YEAR > 2012))", "Othre", "AGE_AT_MIGRATION >= 16 | YEAR - YRSUSA1 != YRIMMIG | CITIZEN == 2", "AGE_IN_2012 > 31 | YRIMMIG >= 2007 | AGE_AT_MIGRATION >= 16", 
                                     "YEAR > 2012 | AGE_AT_MIGRATION >= 16 | CITIZEN!=3 | (2012-BIRTHYR) > 30", "AGE_AT_MIGRATION >= 16 | AGE_IN_2012 >= 31 | YRIMMIG > 2007 | CITIZEN != 3 | EDUC < 6 | VETSTAT != 0", "(AGE_AT_MIGRATION < 16) & (AGE_IN_2012 > 31 | AGE_AT_MIGRATION >= 16 | YRIMMIG >= 2007 | CITIZEN != 3)", 
                                     "(AGE_AT_MIGRATION BETWEEN 13 AND 18) & (AGE_AT_MIGRATION < 16))", "(AGE_AT_MIGRATION BETWEEN 15 AND 16) & (AGE_AT_MIGRATION == 16)", "(AGE_AT_MIGRATION < 30) & (AGE_AT_MIGRATION BETWEEN 16 AND 32)", "None", "AGE_AT_MIGRATION BETWEEN 16 AND 17"),
                        new = c("Other", "< 16", "None", "Not 16", "<= 16", "NA", "Any", "< 15", 
                                "Multistep Condition", "> 16", 
                                "Other", 
                                "Other", 
                                "Other", "Multistep Condition", 
                                "Multistep Condition", 
                                "< 16", 
                                "Multistep Condition", "Multistep Condition", "Other", 
                                "Other", "Other", "Multistep Condition", 
                                "Multistep Condition", "Other", "Multistep Condition", "Multistep Condition", 
                                "Multistep Condition", "Multistep Condition", "Multistep Condition", 
                                "Other", "Other", "Other", "None", "Other"))

fixdat_bpl = data.table(original = c("Mexican-Born", "None", "Non-US Born", "NA", 
                                     "Hispanic-Mexican or Mexican-Born", "Central America-Born", 
                                     "((AGE_IN_2012 < 31 & AGE_AT_MIGRATION <=16 & CITIZEN == 3 & HISPAN == 1 & BPL == 200) | (AGE_IN_2012 < 31) & (BPL == 200)", 
                                     "(BPL == 200) & (BPL == 200.)", "BIRTHYR BETWEEN 1978 AND 1980 | (BIRTHYR == 1977 & BIRTHQTR > 2) | (BIRTHYR == 1981 & BIRTHQTR < 3) & HISPAN BETWEEN 1 AND 4 & (BPLD != 20000 & BPL != 999) & (YRIMMIG BETWEEN 997 AND 2006) & AGE_AT_MIGRATION < 16 & (EDUCD >= 60 | VETSTAT == 2) & (AGE_IN_2012 >= 31 | YEAR < 2012"),
                        new = c("Mexican-Born", "None", "Non-US Born", "None", 
                                "Hispanic-Mexican or Mexican-Born", "Central America-Born", 
                                "Mexican-Born", 
                                "Mexican-Born", "Mexican-Born"))

fixdat_citizen = data.table(original = c("Non-Citizen", "", "Other", "None", "Foreign-Born", "NA", 
                                         "Non-Citizen or Naturalized After 2012", "Non-Citizen or Naturalized", 
                                         "Citizen", "Multistep Condition", "Natural-Born Citizen", "CITIZEN IN (2, 3)", 
                                         "(CITIZEN == 3))) & (CITIZEN == 3)", "Naturalized Citizen",
                                         "(CITIZEN != 2) & (CITIZEN != 4)", "(CITIZEN > 0) & (CITIZEN == 1)", 
                                         "(CITIZEN != 0) & (CITIZEN == 1)", "INLIST(CITIZEN,2,3)", 
                                         "(CITIZEN == 3) & (CITIZEN == 3) | YEAR <= 2012)", 
                                         "(CITIZEN == 3) & (CITIZEN == 3) | YEAR <=2012)", 
                                         "YEAR < 2012 | !(AGE_AT_MIGRATION BETWEEN 0 AND 15) | AGE_IN_2012 >= 31 | YRIMMIG > 2007 | CITIZEN != 3", 
                                         "AGE_AT_MIGRATION >= 16 | YRIMMIG > 2007 | BIRTHYR > 1981 | CITIZEN != 3 | YEAR <= 2012", 
                                         "AGE_AT_MIGRATION >= 16 | CITIZEN != 3 | AGE_IN_2012 >= 31 | YRSUSA1 < 5 | YRIMMIG > 2007", 
                                         "CITIZEN != 3 | YEAR == 2011", "CITIZEN != 3 | !(EDUC >= 6 | VETSTAT == 2) | AGE_AT_MIGRATION >= 16 | AGE_IN_2012 > 31 | (2012 - BIRTHYR <= 25) | BPL != 200 | MIGPLAC1 >= 100 | YRNATUR < 2013 | YRIMMIG > 2012",
                                         "AGE_AT_MIGRATION >= 16 | YEAR - YRSUSA1 != YRIMMIG | CITIZEN == 2",
                                         "YEAR > 2012 | AGE_AT_MIGRATION >= 16 | CITIZEN!=3 | (2012-BIRTHYR) > 30", 
                                         "BIRTHQTR <= 2)) | YRIMMIG > 2007 | CITIZEN != 3", 
                                         "AGE_AT_MIGRATION >= 16 | AGE_IN_2012 >= 31 | YRIMMIG > 2007 | CITIZEN != 3 | EDUC < 6 | VETSTAT != 0", 
                                         "(CITIZEN == 3) & (AGE_IN_2012 > 31 | AGE_AT_MIGRATION >= 16 | YRIMMIG >= 2007 | CITIZEN != 3)"),
                            new = c("Non-Citizen", "None", "Other", "None", "Foreign-Born", "None", 
                                    "Non-Citizen or Naturalized After 2012", "Non-Citizen or Naturalized", 
                                    "Citizen", "Multistep Condition", "Natural-Born Citizen", "Non-Citizen or Naturalized", 
                                    "Non-Citizen", "Naturalized Citizen",
                                    "Other", "Natural-Born Citizen", 
                                    "Natural-Born Citizen", "Non-Citizen or Naturalized", 
                                    "Non-Citizen", 
                                    "Non-Citizen", 
                                    "Multistep Condition", 
                                    "Multistep Condition", 
                                    "Multistep Condition", 
                                    "Multistep Condition", "Multistep Condition",
                                    "Multistep Condition",
                                    "Multistep Condition", 
                                    "Multistep Condition", 
                                    "Multistep Condition", 
                                    "Multistep Condition"))

fixdat_educvet = data.table(original = c("HS Grad or Veteran", "HS Grad", "HS Grad and Non-Veteran", "None", "12th Grade or Veteran", 
                                         "Multistep Condition", "Other Education", "HS Grad or Non-Veteran", "HS Grad or In School", 
                                         "HS Grad or Veteran or In School", "Other Education or Veteran", "Other Education or Non-Veteran", 
                                         "HS Grad and Veteran", "Other", "EDUC BETWEEN 6 AND 11 & ", " & (EDUCD >= 62) & ((EDUCD >= 62))", 
                                         "(EDUC >= 6) & (EDUC >= 06) & ", "EDUC >= 6 &  & VETSTAT == 0", " & EDUCD < 62 & VETSTAT != 2", " & EDUCD >= 61", "12th Grade",
                                         
                                         " & EDUCD >= 062 & VETSTAT > 0 | (INCSS > 0 & INCSS < 99999) | (INCWELFR > 0 & INCWELFR < 99999) | INCSUPP > 0", " & EDUCD >= 62 & ((VETSTAT > 0 | (INCSS > 0 & INCSS < 99999) | (INCWELFR > 0 & INCWELFR < 99999) | INCSUPP > 0)) & (VETSTAT != 2)", 
                                         "Other Education", "HS Grad or Non-Veteran", "HS Grad or In School", "HS Grad or Veteran or In School", "Other Education or Veteran", "Other Education or Non-Veteran", "HS Grad and Veteran", 
                                         "((EDUCD >= 62) | (EDUCD == 50 & YEAR == 2011) | (EDUC == 40 & YEAR == 2010) | (EDUC == 30 & YEAR == 2009) | (EDUC == 26 & YEAR == 2008)) | VETSTAT == 2", 
                                         "I(EDUCD IN (62, 63, 65)) | (EDUCD == 64) | (VETSTATD IN (20, 21, 22)) | (EDUC IN (7, 8, 10, 11)) & ", "(BIRTHYR BETWEEN 1982 AND 1985 | (BIRTHYR == 1981 & BIRTHQTR >= 3) | (BIRTHYR == 1986 & BIRTHQTR < 3) & AGE_AT_MIGRATION < 16 & (VETSTAT == 1 | EDUC >= 6) & YRIMMIG < 2007 & 2007 >= YEAR - YRSUSA1 & ", 
                                         "((I(EDUCD IN (62, 63, 65)) | (EDUCD == 64) | (VETSTATD IN (20, 21, 22)) | (EDUC IN (7, 8, 10, 11)))) & ((EDUC IN (7, 8, 10, 11) | EDUCD IN (62, 63, 65) | EDUCD IN (64) | VETSTATD IN (20, 21 ,22) & YEAR >= 2013) & ", 
                                         "((EDUC >= 6 | VET01LTR == 2 | VET90X01 == 2)) & ((((BIRTHYR > 1981 | (BIRTHYR == 1981 & BIRTHQTR < 3)) & (BIRTHYR < 1986 | (BIRTHYR == 1986 & BIRTHQTR > 2))) & CITIZEN == 3 & (EDUC >= 6 | VET01LTR == 2 | VET90X01 == 2) & YEAR > 2012) & ",
                                         " & (EDUCD BETWEEN 63 AND 116) & ((((BIRTHYR >= 1982) | (BIRTHYR == 1981 & BIRTHQTR >= 3)) & AGE_AT_MIGRATION < 16 & ((EDUCD BETWEEN 63 AND 116) | VETSTAT == 2) & YRIMMIG < 2007)) & (VETSTAT == 1) & ((((BIRTHYR >= 1982) | (BIRTHYR == 1981 & BIRTHQTR >= 3)) & AGE_AT_MIGRATION < 16 & ((EDUCD BETWEEN 63 AND 116) | VETSTAT == 2) & YRIMMIG < 2007))",
                                         " & ((EDUCD >= 60 | VETSTAT == 2)) & ((BIRTHYR BETWEEN 1978 AND 1980 | (BIRTHYR == 1977 & BIRTHQTR > 2) | (BIRTHYR == 1981 & BIRTHQTR < 3) & HISPAN BETWEEN 1 AND 4 & (BPLD != 20000 & BPL != 999) & (YRIMMIG BETWEEN 997 AND 2006) & AGE_AT_MIGRATION < 16 & (EDUCD >= 60 | VETSTAT == 2) & (AGE_IN_2012 >= 31 | YEAR < 2012))", 
                                         "(BIRTHYR BETWEEN 1977 AND 1980 | (BIRTHYR == 1976 & BIRTHQTR >= 3) | (BIRTHYR == 1981 & BIRTHQTR < 3) & AGE_AT_MIGRATION < 16 & (VETSTAT == 1 | EDUC >= 6) & YRIMMIG < 2007 & 2007 >= YEAR - YRSUSA1 & ", "AGE_AT_MIGRATION >= 16 | (YRSUSA1 < 5) | (CITIZEN!=3) | !((YEAR + .5 - (BIRTHYR + BIRTHQTR/4)) < 31) | !((SCHOOL == 2)|(VETSTAT == 2)|(EDUC BETWEEN 6 AND 11)) | (YEAR < 2013 | YEAR > 2016) & ", 
                                         "AGE_AT_MIGRATION >= 16 | AGE_IN_2012 > 31 | YRIMMIG > 2006 | EDUC BETWEEN 1 AND 5 & ", " & AGE_AT_MIGRATION > 16 | !((BIRTHYR > 1981 & BIRTHQTR >= 3) | (BIRTHYR >= 1982)) | YRIMMIG > 2007 | !(SCHOOL == 2 | EDUCD >= 62)", "Multistep Condition", 
                                         "YEAR < 2012 | (YEAR >= 2012 & (BIRTHYR BETWEEN 1977 AND 1980 | (BIRTHYR == 1981 & BIRTHQTR < 3) | (BIRTHYR == 1976 & BIRTHQTR > 2)) & YRIMMIG < 2007 & AGE_AT_MIGRATION < 16 & (EDUC > 6 | VETSTAT == 2 & ", "AGE_AT_MIGRATION >= 16 | AGE_IN_2012 >= 31 | YRIMMIG > 2007 | CITIZEN != 3 | EDUC < 6 | VETSTAT != 0 & ", 
                                         " & (YEAR - AGE) < 1981 | AGE - YRSUSA1 > 16 | YRIMMIG > 2012 | (EDUCD < 62 & VETSTAT != 2)", " & AGE_IN_2012 > 31 | AGE_AT_MIGRATION >= 16 | YEARSUSA1 < 6 | !(SCHOOL == 2 | EDUCD >= 63) | YEAR <= 2013", "((I(EDUCD IN (62, 63, 65)) | (EDUCD == 64) | (VETSTATD IN (20, 21, 22)) | (EDUC IN (7, 8, 10, 11)))) & ((EDUC IN (7, 8, 10, 11) | EDUCD IN (62, 63, 65) | VETSTATD IN (20, 21 ,22)) & ", 
                                         " & (BIRTHYR >= 1982) | (BIRTHYR == 1981 & BIRTHQTR >= 3)) | (CITIZEN != 3) | (EDUCD < 62", " & BPL == 200 & AGE BETWEEN 15 AND 35 & CITIZEN == 3 & CITIZEN == 3 & (YEAR < 2012 | AGE < 15 | (SCHOOL != 2 & SCHOOL != 1 & EDUCD >= 62) | AGE_AT_MIGRATION > 16 | YRIMMIG > 2007 | AGE_IN_2012 >= 31", " & YEAR < 2012 | AGE < 15 | (SCHOOL != 2 & SCHOOL != 1 | EDUCD >= 62) | AGE_AT_MIGRATION > 16 | YRIMMIG > 2007 | AGE_IN_2012 >= 31"),
                            new = c("HS Grad or Veteran", "HS Grad", "HS Grad and Non-Veteran", "None", "12th Grade or Veteran", 
                              "Multistep Condition", "Other Education", "HS Grad or Non-Veteran", "HS Grad or In School", 
                              "HS Grad or Veteran or In School", "Other Education or Veteran", "Other Education or Non-Veteran", 
                              "HS Grad and Veteran", "Other", "HS Grad", "HS Grad", 
                              "HS Grad", "HS Grad and Non-Veteran", "Other", "12th Grade", "12th Grade",
                              "HS Grad and Veteran", "HS Grad", 
                              "Other Education", "HS Grad or Non-Veteran", "HS Grad or In School", "HS Grad or Veteran or In School", "Other Education or Veteran", "Other Education or Non-Veteran", "HS Grad and Veteran", 
                              "HS Grad or Veteran or In School", 
                              "HS Grad or Veteran", "HS Grad or Non-Veteran", 
                              "HS Grad or Veteran", 
                              "HS Grad or Veteran",
                              "HS Grad",
                              "HS Grad or Veteran", 
                              "HS Grad or Non-Veteran", "Multistep Condition", 
                              "Multistep Condition", "Multistep Condition", "Multistep Condition", 
                              "Multistep Condition", "Multistep Condition", 
                              "Multistep Condition", "Multistep Condition", "Multistep Condition", 
                              "Multistep Condition", "Multistep Condition", "Multistep Condition"))

fixdat_yrimmig = data.table(original = c("< 2007", "<= 2007", "None", "NA", "Any Year", "Other", "< 2012", "Not 2007", ">= 2007", "Multistep Condition", 
                                         "<= 2012", "Not 2012", "YRIMMIG > 2011, BIRTHYR > 1980, YEAR >= 2012", "> 2012", "> 2007", 
                                         "(YRIMMIG BETWEEN 2002 AND 2012) & (!YRIMMIG == 2007) & (YRIMMIG BETWEEN 2008 AND 2012)", 
                                         "BIRTHYR < 1982 | AGE_AT_MIGRATION >= 16 | YRIMMIG > 2007", "AGE - YRSUSA1 >= 16 | AGE_IN_2012 >= 31 | YRIMMIG >= 2007", 
                                         "(YRIMMIG <= 2012) & (AGE_AT_MIGRATION >= 16 | YEAR - YRSUSA1 != YRIMMIG | CITIZEN == 2)", 
                                         "AGE_IN_2012 > 31 | YRIMMIG >= 2007 | AGE_AT_MIGRATION >= 16", "BIRTHQTR > 2) | YRIMMIG >= 2008",
                                         "BIRTHQTR <= 2)) | YRIMMIG > 2007 | CITIZEN != 3", "BIRTHYR < 1981 | AGE_AT_MIGRATION >= 15 | YRIMMIG > 2007"),
                            new = c("< 2007", "<= 2007", "None", "None", "Any Year", "Other", "< 2012", "Not 2007", ">= 2007", "Multistep Condition", 
                                    "<= 2012", "Not 2012", ">= 2012", "> 2012", "> 2007", 
                                    "Other", 
                                    "Multistep Condition", "Multistep Condition", 
                                    "<= 2012", 
                                    "Multistep Condition", "Multistep Condition",
                                    "Multistep Condition", "Multistep Condition"))
